### ISSUE TITLE
BioSample Export for `CanCOGeN-COVID` template

### ISSUE THREAD

**Issue by cmrn-rhi** [cidgoh/DataHarmonizer#139]
# BioSample mappings for `CanCOGeN-COVID` template
**Priority:** _**High**_

**Description:** Make it so the DataHarmonizer can convert and export the `CanCOGeN-COVID` template into the `BioSample Pathogen` template.

**To-Dos:**
- [x] Field Mappings
  - [x] Field Mapping Review
- [ ] Implementation into DataHarmonizer
- [ ] Export Testing
- [ ] Release

**Comment by cmrn-rhi** [comment]
## Field Mappings (version 1)
The following `xlsx` contains **pre-review** field mapping information and suggestions. Any values that are direct field-to-field mappings have already been added to the DataHarmonizer `CanCOGeN-COVID` [online spreadsheet template](https://docs.google.com/spreadsheets/d/1jPQAIJcL_xa3oBVFEsYRGLGf7ESTOwzsTSjKZ-0CTYE/edit#gid=886509415) under the column `EXPORT_BIOSAMPLE`.

More nuanced mapping information is contained in the attached `xlsx` along with suggestions. An updated (reviewed) version that addresses areas in need of clarification will be uploaded shortly.

**Attachment:** 
[PHA4GE_BioSample_template_2021_DH-Mappings-1.xlsx](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/files/5997832/PHA4GE_BioSample_template_2021_DH-Mappings-1.xlsx)

**Comment by cmrn-rhi** [comment]
## Field Mappings (version 2) _- reviewed_
Integrated feedback from @griffie into the `xlsx` and the `EXPORT_BIOSAMPLE` column of the DataHarmonizer `CanCOGeN-COVID` [online spreadsheet template](https://docs.google.com/spreadsheets/d/1jPQAIJcL_xa3oBVFEsYRGLGf7ESTOwzsTSjKZ-0CTYE/edit#gid=886509415).

**Attachment:**
[PHA4GE_BioSample_template_2021_DH-Mappings-2.xlsx](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/files/6000013/PHA4GE_BioSample_template_2021_DH-Mappings-2.xlsx)

**Comment by ddooley** [comment]
@cmrn-rhi  This can be closed, right?

**Comment by ddooley** [comment]
All done a while back
