### ISSUE TITLE
save/export to JSON

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#209]
Has there been any discussion about saving to or exporting to formats other than rectangular tables?

Maybe this is a far fetched stretch for a project based on Handsontable. I did find this: https://forum.handsontable.com/t/export-to-json/3925

**Comment by ddooley** [comment]
A request from NML has come in for JSON export format so this is more of a priority for us.  We will implement this on the LinkML version of DH.

**Comment by ddooley** [comment]
On https://github.com/cidgoh/DataHarmonizer/pull/344 there is now a save-as-json option.  
This doesn't have load-as-json yet though.

**Comment by ddooley** [comment]
Now save and load are in master!
