### ISSUE TITLE
template meta builder (entry of select lists for lazy people)

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#212]
There is a `geo_loc_name` section in the CanCOGeN template. I assume somebody entered the content below mostly by hand?

I would be interested in a tool that could populate the following into the template just by specifying the parent term GAZ:00002561 'Province (Canada)'. Then the user could add, delete or modify any of that.

_Or instead of a tool, it could just be some documentation/hints... see further down_

Ontology ID | Meaning (LinkML) | parent class | label
-- | -- | -- | --
ID |   | SC % |  
GAZ_00002566 |   | geo_loc_name (state/province/territory) | Alberta
GAZ_00002562 |   | geo_loc_name (state/province/territory) | British Columbia
GAZ_00002571 |   | geo_loc_name (state/province/territory) | Manitoba
GAZ_00002570 |   | geo_loc_name (state/province/territory) | New Brunswick
GAZ_00002567 |   | geo_loc_name (state/province/territory) | Newfoundland and Labrador
GAZ_00002575 |   | geo_loc_name (state/province/territory) | Northwest Territories
GAZ_00002565 |   | geo_loc_name (state/province/territory) | Nova Scotia
GAZ:00002574 |   | geo_loc_name (state/province/territory) | Nunavut
GAZ_00002563 |   | geo_loc_name (state/province/territory) | Ontario
GAZ_00002572 |   | geo_loc_name (state/province/territory) | Prince Edward Island
GAZ_00002569 |   | geo_loc_name (state/province/territory) | Quebec
GAZ_00002564 |   | geo_loc_name (state/province/territory) | Saskatchewan
GAZ_00002576 |   | geo_loc_name (state/province/territory) | Yukon

## Sample  documentation

"Run the following query at" http://sparql.hegroup.org/sparql/

```SPARQL
PREFIX  GAZ:  <http://purl.obolibrary.org/obo/GAZ_>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  oio:  <http://www.geneontology.org/formats/oboInOwl#>

SELECT  (str(?i) AS ?Ontology_ID) ("" AS ?Meaning_LinkML) 
("geo_loc_name (state/province/territory)" AS ?parent_class) (str(?l) AS ?label)
WHERE
  { GRAPH <http://purl.obolibrary.org/obo/merged/GAZ>
      { ?s  rdfs:subClassOf  GAZ:00002561 ;
            rdfs:label       ?l ;
            oio:id           ?i
      }
  }
```

**Comment by ddooley** [comment]
P.s. our previous GAZ and DO dynamic lookup system went straight to OLS API. You can see it in action in example form https://genepio.org/geem/form.html#GENEPIO:0001777 - any of the "lookup choice" fields will provide a popup if you provide an initial choice to start from. (Its a prototype we would redo the code for btw).
If OntoBee isn't a solution would OLS be for dynamic lookup?

**Comment by turbomam** [comment]
Thanks @ddooley 

I think I was too eager to create an issue here. I'm well on my way to creating templates by parsing LinkML files. I think that should be self sufficient and not require any external lookups. I'll share my code soon.

direct answer to your question: yes, I use OLS a lot and using it for this poorly worded issue would make sense, if external lookups were required.

**Comment by turbomam** [comment]
Here's my work in progress for creating a [DataHarmonizer template from a LinkML schema](https://github.com/microbiomedata/nmdc-metadata/blob/issue-375/notebooks/build_dh_soil_template.ipynb)

I've shared the converted website as a [github page](https://turbomam.github.io/DataHarmonizer/main.html?template=soil)

None of this is guaranteed to stay in the same location or to be up 100% of the time
