### ISSUE TITLE
CanCOGeN template: "HUMAN" case change in LIMS export

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#229]
Currently the "Homo sapiens" value under Host (scientific name) exports in LIMS format as HUMAN (as a relic of the previous CNPHI requirements). 
"Homo sapiens" now needs to export as "Human" to be compatible with NML LIMS. 

However, the NML LIMS export format didn't originally have any value in it in the DH template so I think 'HUMAN" must be as a result of some specific coding. Can you check and update as necessary, pretty please?
I also added "Human" in NML export in the DH template.

Thanks!

**Comment by ddooley** [comment]
Currently a few values are capitalized ... should they all be title case?
![image](https://user-images.githubusercontent.com/4000582/139941241-67c618b4-8b48-4f34-8ba4-fb9be8590a7c.png)

**Comment by griffie** [comment]
Oh, I think those are relics from the past as well. I doubt we will get many more animal/enviro samples as all the prov stuff is Human. So let's leave the others as-is for the time being.

**Comment by ddooley** [comment]
Done in "vocabulary update" branch.
