### ISSUE TITLE
CanCOGeN template: all null values should be lower case with the first letter of each word capitalized

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#230]
Currently in the NML LIMS export, all the null values reflect those offered by the DH, which are lower case with the first letter of each word capitalized. This is what is needed for LIMS.

However, some users input null values in the free text fields. When they do this programmatically, sometimes those null values are all caps.

Can we ensure that any null value in any field has the proper capitalization?
e.g. "NOT PROVIDED" or "not provided" or "Not provided" should always be "Not Provided".

Thanks!

**Comment by ddooley** [comment]
So each free text field needs to be searched for any of the standard null values, and have Title caps applied to them?  This is somewhat computationally intensive; Can we at least say that the entire value of such a field will be a null value? That will speed up comparison.

**Comment by griffie** [comment]
Sure. Let's do that.

**Comment by ddooley** [comment]
I've implemented this just for NML LIMS, in the "vocabulary update" branch.
