### ISSUE TITLE
VirusSeq export from CanCOGeN template: automate addition of study_ID

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#231]
In the VirusSeq export from the CanCOGeN template, there is a field that is added automatically called study_ID.
The study_ID is a user-defined ID that is being used to group datasets from different submitters (i.e. provinces at this point, could be others in the future).

The study_ID for each province is unique.

To save the curator from having to add the study_ID to all the records being submitted to the portal manually (can sometimes be in the 1000's), can we automate the addition of the study_ID according to the lab name?

We have the list of study_IDs that correspond to each prov lab e.g. the study_ID for the BCCDC is "BCCDC-BC".
The list of study_IDs and corresponding labs is given in this google spreadsheet:
https://docs.google.com/spreadsheets/d/1L6ebnKLYQklMAaH90vQcDBLtAmGMeBMcYCEqhynxJhI/edit?usp=sharing

**Comment by ddooley** [comment]
So that list is complete now?  The lookup would be easy enough to add, but would have to be hardcoded into export.js for now.

**Comment by ddooley** [comment]
field autofill function added to "vocabulary update" branch.
