### ISSUE TITLE
VirusSeq export from CanCOGeN template: automate addition of % symbol to "coverage" value

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#232]
In the VirusSeq export from the CanCOGeN template, the breadth of coverage value is exported as a string.

The VirusSeq schema requires a "%" symbol after the value, which currently has to be inserted manually by the curator.
The % symbol is part of the field definition and so not inserted in the DH or in NML LIMS.

Can we automate the addition of the "%" symbol after the value in the breadth of coverage export? e.g. 89 in the DH appears as 89% under breadth of coverage in the VirusSeq export?

**Comment by ddooley** [comment]
Ok, done, and on branch "vocabulary update" shortly.
