### ISSUE TITLE
french accents removed from client descriptions

### ISSUE THREAD

**Issue by nknox** [cidgoh/DataHarmonizer#235]
In the latest version of DH, the french accents are removed. 
E.g. Laboratoire de sant publique du Qu bec (LSPQ) ; New Brunswick - Vitalit Health Network (é at the end of Vitalit)

**Comment by ddooley** [comment]
If you are seeing this in the DH menu or in the NML-LIMS export of this data?  If the latter, then next release has a fix that tweaks the DH NML-LIMS export file format so Excell can display the accents correctly.

**Comment by ddooley** [comment]
I will close this now.  We will reopen if you find its still an existing issue?
