### ISSUE TITLE
CanCOGeN template: restore purpose of sequencing hierarchy in the picklist

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#239]
Purpose of Sequencing is an important piece of information for evaluating sampling strategy.
Previously the hierarchy for the purpose of sequencing tags as recorded in the gsheet was available in the GUI picklist.
The hierarchy is helpful as it makes the list more scannable, and relates tags to each other.

Now all the tags appear as a flat list.

Can we restore the hierarchy in the pick list?

**Comment by ddooley** [comment]
At moment our multi-select control doesn't display a hierarchy, so this happened when we switched purpose of sequencing to multi-select.  There's a bit of a challenge as I recall because this is a 3rd party library but I'll check it out.

**Comment by griffie** [comment]
We have been discouraging multi-select (despite enabling it).

I would prioritize the hierarchy over the multi-select, if that's a thing.

**Comment by ddooley** [comment]
Ok I got the hierarchy working in multi-select for next release!
