### ISSUE TITLE
CanCOGeN template: Order of new fields in LIMS export

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#241]
We just added a new field called "case ID", and renamed 2 previous fields which are now called "Related specimen relationship type" and "Related specimen primary ID". Because they have official NML export names (capitalized) they need to appear in special places in the output.

Can "PH_CASE_ID" please appear in the output after "PH_ID_NUMBER_PRIMARY", followed by "PH_RELATED_PRIMARY_ID"?
e.g.
PH_ID_NUMBER_PRIMARY
PH_CASE_ID
PH_RELATED_PRIMARY_ID

Can "PH_RELATED_RELATIONSHIP_TYPE" appear after "PH_SPECIMEN_TYPE"?

Thanks!

**Comment by ddooley** [comment]
Done!
