### ISSUE TITLE
CanCOGeN template: remove null values concatenated in PH_TRAVEL in LIMS export

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#242]
Currently travel information is concatenated into PH_TRAVEL in the NML-LIMS export.

Often, most fields are populated with null values. Sometimes, there are multiple null values and one or two nuggets of travel info.
e.g. Not Provided;Not Provided;Not Provided;Not Provided;Not Provided;HALIFAX

If there are multiple null values in PH_TRAVEL, can we remove them so that only the non-null values remain?

If there are only null values, can we remove all but one of them to indicate the field was addressed, but no more?

Thanks!

**Comment by ddooley** [comment]
I had a vague memory that NML was actually parsing the semi-colon delimited list back into multiple fields?  If so then at least the semi-colon placeholders have to be kept? But they could be empty values, eg.   Missing;;;;; ?  But if they aren't demultiplexing back into city, country etc fields, then yes we can collapse the list into a minimal one.

**Comment by griffie** [comment]
They are not separating into different fields. What you are remembering may be a relic of CNPHI (which is different than LIMS). 

On the LIMS end, everything is just going into PH_TRAVEL.

**Comment by ddooley** [comment]
Ok, done!
