### ISSUE TITLE
Does the main branch still use data.tsv as input?

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#243]

**Comment by turbomam** [comment]
I'm developing in https://github.com/microbiomedata/DataHarmonizer. We are still using `data.tsv` to specify our DataHarmonizer interfaces. We might switch to whatever methods you have for using LinkML as input after February.

Here's a summary of your commits that we don't have yet. If I just take all of these, will the `main` branch still have `script/make_data.py`?

**Comment by turbomam** [comment]
https://github.com/microbiomedata/DataHarmonizer/compare/master...cidgoh:master

**Comment by ddooley** [comment]
Yes it does! And main branch still uses make_data.py .  Not sure about the "summary of your commits that we don't have yet", but besides one master commit for issue #66 , the current release has all commits put towards master; the WIP LinkML data structure branch doesn't use data.tsv and has many commits towards it but when they become the main source code, it would be expected that information sourced from data.tsv would be sourced directly from linkml templates instead.

**Comment by ddooley** [comment]
Ah, yes, you can take all those commits.  They are just about specific template vocabulary updates except the last one which is inconsequential at moment too.

**Comment by turbomam** [comment]
Thanks @ddooley
