### ISSUE TITLE
What's the Null values section in the double-click-the-header help?

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#244]

**Comment by turbomam** [comment]
Possibly see also #243

**Comment by ddooley** [comment]
At moment there is a feature in DH that allows the "data status" column of a template (in data.tsv) to be a (nominal) list of permitted null values - e.g. "Not Applicable; Missing; Not Collected; Not Provided; Restricted Access" to be added in addition to whatever field validation is applicable to a field (decimal, date, enumerated list).  The double click header help lists off the allowed null value tokens for the field.

**Comment by turbomam** [comment]
Thanks, that makes sense

**Comment by ddooley** [comment]
The ability to specify multiple ranges provides a solution for having null value categorical choices added to any desired field, so will implement that solution, per bottom of linkml/linkml#178

**Comment by ddooley** [comment]
This is now done on the WIP-validation branch which will be merged soon.
