### ISSUE TITLE
CanCOGeN template: updates to NML LIMS fields in LIMS export and correcting output order

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#250]
I've added 3 new LIMS export fields to the LIMS export output from the CanCOGeN template.
These all caps fields need to be moved in the LIMS export output so that they appear in the correct place.

Can PH_HOST_HEALTH_OUTCOME appear after PH_HOST_HEALTH_DETAILS?
Can PH_LIBRARY_PREP_KIT appear after PH_SEQUENCING_DATE?

The vaccination section has been updated and restructured. New fields have been added, while others have been removed.
All fields in the LIMS export (except "number of vaccine doses received") should now be concatenated into the LIMS export field "PH_VACCINATION_HISTORY".
Can PH_VACCINATION_HISTORY appear after HC_SYMPTOMS?

Thanks!

**Comment by ddooley** [comment]
done!
