### ISSUE TITLE
section-based jump and show/hide

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#251]
Hi, @ddooley and colleagues

NMDC would like to see section-based jumping and show/hide, like you have implemented for columns. Is that anything you could do, or help us with by providing hints? 

See https://github.com/microbiomedata/DataHarmonizer/issues/70

**Comment by ddooley** [comment]
The latest DH now has section based jumping feature - Sections are now listed along with the underlying fields.

However about section show/hide, how should that be set up?  Do we just allow one section to be on at a time, or show all? I think we'd not want "show required" or "show required or recommended" active at same time.

**Comment by ddooley** [comment]
The master branch now has a tentative section show/hide menu for feedback.
