### ISSUE TITLE
CanCOGeN template: add corrections for null values in all fields upon LIMS export

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#256]
Right now the DH corrects spacing and capitalization of null values in required fields, but errors in null values entered in the optional fields are causing problems in submissions to the data portal.

Can we add some code for the NML LIMS export to search all fields for null values, and once identified, to correct for errant spacing and capitalization?

**Comment by ddooley** [comment]
Done on DH draft!  Note that though some fields like GISAID Accession are marked as capitals, if content is a null value string, that will be adjusted for NML LIMS export, i.e. "MISSING" is converted to "Missing" on export.
