### ISSUE TITLE
Remove "draft CanCOGeN" label from ntologized terms in EBI OLS

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#257]
Right now all of the ontologized fields pertaining to COVID in GenEpiO show up in EBI OLS with the label "draft CanCOGeN:XXX".

That is confusing for users as the ontologized fields are meant to be universal and only implemented in the PHA4GE spec right now. So users who look up the fields in OLS will see the CanCOGeN label. Can we make the generic fields NOT spec-specific, keeping the current IDs? (So the current IDs become generic ontology terms that can be used across specs without a particular label)?

Spec-specific IDs could be developed in the next iteration.

Currently, the CanCOGeN label makes the fields hard to find and confusing for international users who have been sending us issues that we need to address.

**Comment by ddooley** [comment]
This will be updated in next OLS refresh. Note that Ontobee is having some problems loading some ontologies; it needs a complete reload of GenEpiO at moment.  This has been reported to Ontobee.
