### ISSUE TITLE
Create COVID ontology term subset for the hackathon (Feb 2022)

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#258]
To make our COVID-related terms more explorable by the international community - in particular the participants of the upcoming COVID ontology hackathon - can we make a collection available e.g. "GenEpiO COVID-19 Ontology Slim"?

**Comment by ddooley** [comment]
I believe this is done via Covid19 slim that shows in GenEpiO?  Outstanding question is whether to make a separate file of this?

**Comment by ddooley** [comment]
We're eliminating slims in GenEpiO so closing this.
