### ISSUE TITLE
CanCOGeN template: Maximums in collection dates

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#259]
We are having issues with collection dates in the future (likely due to the 2021/2022 change over e.g. 2022-12-30 instead of 2021-12-30).

Can we put in a safeguard in the validation code to check that collection dates are not beyond "today" (whatever the user's computer registers as "today").

**Comment by ddooley** [comment]
I've added functionality that putting the string "{today}" into a date field's "min value" or "max value" will trigger a validation check against whatever {today} evaluates to (ignoring time zones).
