### ISSUE TITLE
CanCOGeN template: validation to check collection dates come before sequencing dates

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#261]
Samples are collected first before they are sequenced.
But currently we have some errors cropping up where collection dates are later than the entered sequencing dates.

Can the DH validation flag seq dates that are earlier than collection dates as errors?

**Comment by ddooley** [comment]
This test is now in master, by allowing "min value" and "max value" to reference not only static dates, and {today}, but as well other fields matched using "{field name}"
