### ISSUE TITLE
Usage notes for linkml-datastructure branch?

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#264]
I'm thinking about retiring the [LinkML->`data.tsv` converter I wrote for NMDC](https://github.com/microbiomedata/DataHarmonizer/blob/master/sheet2dataharmonizer/converters/linkml2dataharmonizer.py) in the next month or so.

The documentation/README for the `master` branch is pretty good. Is there anything like that for `linkml-datastructure`?

**Comment by ddooley** [comment]
No comparable documentation yet though the functionality is expected to deviate in only minor ways so I'm expecting most documentation to be adapted with field name changes basically and a few new columns.  However I have to do one more development push to get the last 20% of functionality moved over to linkml-datastructure.  

Are you speaking of retiring it in conjunction with having the linkml-datastructure version up and running? Or is it that the need to work on final linkml MiXS standards is easing off?

To be clear,

**Comment by ddooley** [comment]
Documentation is up at https://github.com/cidgoh/DataHarmonizer/wiki/DataHarmonizer-Templates and https://github.com/cidgoh/DataHarmonizer/wiki/Managing-schema.yaml so I am closing this.
