### ISSUE TITLE
bulleted guidance, like the bulleted examples

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#265]
Examples appear as bulleted lists in the `linkml-datastructure` branch, right?

Could that be applied to guidance, too? Or some other style to show key/value pairs for `see_also`s, minimum and maximum values, etc?

See also #264

**Comment by ddooley** [comment]
Yes, I think any one-to-many relation could get a key title and bulleted values if say more than one item, in terms of the display?  Or if just one item then [key]: [value] ?

**Comment by ddooley** [comment]
This is now done insofar as a simple markup interpreter is rendering the column header help and sidebar help content.
