### ISSUE TITLE
collaborate on linkml branch

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#267]

**Comment by turbomam** [comment]
- `linkml.py` behavior for creating the template menu in the `menu.js`?
- section definition and ordering
- what slot attributes are applied to the DH interface, esp help dialogs
- which classes should be considered eligible to appear in the templates menu?
- contribute Brandon's embedding code in main.js back upstream?
- schema.js replaces data.js

**Comment by turbomam** [comment]
See also notes in issue at https://github.com/turbomam/DataHarmonizer/issues/1

**Comment by ddooley** [comment]
I think Brandon's embedding code is now obsolete re linkml-datastructure branch.  Working on help dialog slot attribute display in separate thread. I'll spruce that up today according to those requests.

**Comment by turbomam** [comment]
> Working on help dialog slot attribute display in separate thread

great!

Can you point me towards any notes about possible improvements to the help dialogs? I was just experimenting with the ways that DH acts on various LinkML slot attributes for either validation or help at https://github.com/microbiomedata/dh_testing

I have some relevant but verbose notes. One could could look for appearances of "help" in https://github.com/microbiomedata/dh_testing/issues/3#issue-1320224735

I could probably formalize that issue comments some if that would be helpful.

**Comment by ddooley** [comment]
I guess dh_testing is private.  Can you get ddooley on there?  Thx!

**Comment by turbomam** [comment]
I made it public

**Comment by ddooley** [comment]
Well, if you want to add stuff to a column help view of a column, then getCommentDict(slot) should be the dictionary to add textual key/values for, and then getComment provides the HTML available to the double click header. Admittedly that function is built into DataHarmoniser class.  I guess it could be overwritten if you wanted a customized display?

renderReference() also uses the very same getCommentDict(slot) as getComment() for each of the slots.

Is that what you needed confirmation about?

**Comment by ddooley** [comment]
It would be good to formalize what you need, or just put in a pull request for more content in getCommentDict(slot)  and getComment() if it is generically applicable for other DH users!
