### ISSUE TITLE
Quality Control Check: GISAID Export

### ISSUE THREAD

**Issue by cmrn-rhi** [cidgoh/DataHarmonizer#272]
Don't have exact details but heard there have been some issue(s) using the GISAID export so I think one of us should do a quality control check on this feature to see if there are any hiccups we can catch.

**Comment by ddooley** [comment]
Is this still an issue?

**Comment by cmrn-rhi** [comment]
@griffie have you happened to do a GISAID export check during recent quality control testing?

**Comment by cmrn-rhi** [comment]
I think this was a comment that stemmed from an NML meeting back in February. So I think if you've checked it out since then we're fine to close this.
