### ISSUE TITLE
In LinkML branch: determine section membership with slot group

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#276]
preferably as an option, in addition to the current use of `is_a` parents

[slot_group definition](https://linkml.io/linkml-model/docs/slot_group/)

Sujay and I will work on this

This is probably the [entry point in main_linkml.js](https://github.com/turbomam/DataHarmonizer/blob/fadb6bc51e98da80d200c99b5e3de99c6281ddc4/script/main_linkml.js#L918-L928)

**Comment by turbomam** [comment]
bump: the linkml datastructure branch does group according to slot_groups now :-) , but it doesn't yet order either sections or columns according to rank.

**Comment by turbomam** [comment]
I think the slot_groups have ranks as well. I'll dig something up now.

**Comment by ddooley** [comment]
As noted on Slack, I missed that “dh_section” is a slot, and under that we have various “sub-classes” entities, which are referenced by slots’ “slot_group” field. I’ll revise section sorting code to take that into account now.

**Comment by ddooley** [comment]
The latest push should fix this.  For sort, I just had to add a call to fetch slot_group specs from overall specification in order to get rank.

**Comment by turbomam** [comment]
Yes, section and column layout looks great now.

Did you say you thought that column jumping would be restored in this push? I tried once in my usual setup and it didn't work for me yet.

**Comment by turbomam** [comment]
Show section isn't working either

**Comment by ddooley** [comment]
There's some odd behaviour with slots that are a subclass of one section but have "slot_group" some other section.  Fields in "MIxS core" seems to be problematic this way re. show section, and jumping to them.  Looking into it.

**Comment by turbomam** [comment]
> There's some odd behaviour with slots that are a subclass of one section but have "slot_group" some other section

Oh! I don't I intended that to happen. I will look into that later today.

**Comment by ddooley** [comment]
Not your problem.  It turns out menu wasn't refreshing list of template sections or jump to fields.  Fixed but have to fix something else before pushing commit on that.

**Comment by ddooley** [comment]
This should be fixed with latest commit.  I didn't catch it earlier because I wasn't doing template change when testing the show/jump functionality.

**Comment by turbomam** [comment]
Showing and jumping work in Chrome, but not after loading data and validating

**Comment by ddooley** [comment]
K.  likely validation causing javascript error that is knocking out other js functions. I will test on your sample data.

**Comment by turbomam** [comment]
I think this is done. @sujaypatil96 may have some ideas for removing some section arrangement functionality that's replicated between the python can javascript components, but that could be another issue.
