### ISSUE TITLE
Validation button in linkml datastructure branch broken

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#281]
Clicking the Validate button shows visual feedback, but there's no "Next Error" or "No Errors" message/buttons

**Comment by ddooley** [comment]
I've done a cursory test on some templates and fields and do get the "Next Error" button showing. Can you give me a dataset that it fails on?  I suspect a particular field type is generating an error.  Yesterday I had to add another commit to fix a .pattern validation issue BTW.

**Comment by turbomam** [comment]
Yeah, sorry, I left that out all my recent issues! I'll post the address for a LinkML file in a minute.

**Comment by turbomam** [comment]
Try this LinkML input: https://raw.githubusercontent.com/microbiomedata/sheets_and_friends/main/artifacts/nmdc_dh.yaml

You could just move it into `template/nmdc_dh/source` in the `linkml-datastructure` branch, overwriting the `nmdc_dh.yaml` that's already in there

Then `make clean; make template/nmdc_dh/schema.js`

You could load this data file: https://raw.githubusercontent.com/microbiomedata/sheets_and_friends/main/data/nmdc_test_data_valid.tsv
