### ISSUE TITLE
Create exclusion list for LinkML classes that don't merit their own DH template

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#282]
For example `quantity value`

**Comment by ddooley** [comment]
I was wondering if this information should be in the form of a JSON file that is loaded before the menu system, and can filter out given menu system entries of form [schema]/[class or slot definition] coming in from any of the template folders?

**Comment by turbomam** [comment]
I don't have any preferences regarding implementation, but will check with other NMDC people to see if they do. Thanks.

**Comment by ddooley** [comment]
This is now implemented in linkml-datastructure branch.
