### ISSUE TITLE
parent issue for testing recently resolved bugs

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#284]
- [x] validation button #281
- [x]  no columns shown when template **with** columns loaded after template **lacking** columns
- more?

**Comment by turbomam** [comment]
That's great! I was going to put together a branch to illustrate the problems I was having, and now I may not have to.

**Comment by ddooley** [comment]
I think I can just download that file and figure out the problem.

**Comment by ddooley** [comment]
I think this is resolved now with latest commit  to the branch.
