### ISSUE TITLE
CanCOGeN template: move border testing fields in LIMS output

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#289]
Two new fields were added to accommodate border testing information in the Host Exposure information section in the DH.
In the LIMS export, the new fields output as
PH_POINT_OF_ENTRY
PH_DAY

They need to appear after PH_TRAVEL in the LIMS export but currently are found nearer to the end of the list.

Can we please shift them to the appropriate spot?

**Comment by ddooley** [comment]
Done!

**Comment by griffie** [comment]
Thank yooooooouuuu!
