### ISSUE TITLE
Column jumping MAY break after show section operation

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#293]
**I can't reproduce what I think I saw. Will continue experimenting.**

In linkml-datastructure branch:

- `make nmdc`
- switch to `nmdc_dh/soil_emsl_jgi_mg` template
- File -> open a sample data file like [nmdc_test_data_valid.tsv](https://drive.google.com/file/d/1hwDGHqyRftnmx1aNS-SHVJo9_pxIIWit/view)
- confirm column rearrangement if necessary. Headers **are** in row 2.
- Experiment with validation. Give two rows identical `globally unique ID`s, or leave one blank, or use an invalid format.
- Settings -> jump to `pH`. That works now!
- Settings -> show section `EMSL`
- Settings -> jump to `pH`

**Comment by ddooley** [comment]
I thought I saw the inability to jump too, but can't recreate it either. Hmm.

**Comment by ddooley** [comment]
I think this is solved now? I will close unless it comes up again.
