### ISSUE TITLE
LinkML slot attributes for driving validations

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#300]
See also #267 

This snippet shows how to list all of the attributes that are applicable to LinkML slots:

```python
from linkml_runtime import SchemaView
meta_url = "https://raw.githubusercontent.com/linkml/linkml-model/main/linkml_model/model/schema/meta.yaml"
meta_view = SchemaView(meta_url)
sis = meta_view.class_induced_slots('slot_definition')
for i in sis:
    print(i.name)
```

Here are some that I think should be used for validations:

slot_attribute | notes
-- | --
maximum_value | works with the NMDC templates now that @pkalita-lbl  PR'ed a float caster in #299.
minimum_value | works with the NMDC templates now that @pkalita-lbl  PR'ed a float caster in #299.
multivalued | todo, along with min and max cardinality? "\|" shouldn't appear   in non-multivalued columns?
identifier | I think that this is being acted upon, like for MIxS' `source_mat_id`, which NMDC   entitles XXX. Makes the column required and enforces uniqueness. Can only be  applied to one column (i.e. one attribute per class). We need some other way to express that other columns should take unique values.
pattern | works, as composed regular expressions
range | I don't think any action is taken on ranges on their own. NMDC has data and code for matching ranges to (regular expression) patterns within the LinkML schema. Is DataHarmonizer still validating based on `xsd` types in the `linkml-datastructure` branch, the way it doe sin the `main` branch? If so, we should make sure common LinkML classes and types are related to the `xsd` types.
string_serialization | NMDC has [data](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=928747012) and [code](https://github.com/microbiomedata/sheets_and_friends/blob/a051b894de4f0e9838e224c35fe12e05b4a02772/sheets_and_friends/modifications_and_validation.py#L111-L151) for matching composed  `string_serialization`s to (regular expression) `pattern`s, but it's really a misuse of `string_serialization`, which is meant to generate strings based on a template of attribute names. We should be doing this though `structured_pattern`s instead. Furthermore, `structured_pattern`s should take advantage of pre-composed chunks from LinkML `settings`. Is there a desire for any of this to happen in real time within DataHarmonizer? We will need to build up a library of `settings` and expansions, along with some understanding of the MIxS grammar, especially the use of `;` and `\|`
structured_pattern | @sujaypatil96  and others are working the expansion of `structured_pattern`s. See `string_serialization` above
required | works
id_prefixes | todo? Value in columns with `id_prefixes` would have to begin with one of the prefixes, then a colon, then some local portion.
maximum_cardinality | todo, along with `multivalued`?
minimum_cardinality | todo, along with `multivalued`?
ifabsent | todo? How would this relate to DataHarmonizer's mechanisms for default values?
range_expression | todo for complex cases?

**Comment by ddooley** [comment]
Latest WIP-validation branch, which will be merged into linkml-datastructure, adds:
-  any_of option for multiple ranges.  Each range has to be datatype or an enumeration. So far no other range_expression option implemented.

I can see we'll have to carefully go through each of these items!
