### ISSUE TITLE
Monekypox-CAN template: Change order PH_SEQUENCING_SUBMITTER in NML-LIMS export

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#309]
New template alert!

A new field was added to the NML-LIMS export from the new Monkeypox-CAN template.
The order of fields in the export needs to be updated.

Can we please have PH_SEQUENCING_SUBMITTER appear after PH_SEQUENCING_CENTRE?

The NML-LIMS export will be drastically reduced due to the removal of a number of extraneous fields (compared to the CanCOGeN template).

**Comment by ddooley** [comment]
Ok, done, and will be available on WIP validation shortly.
