### ISSUE TITLE
Split project into library and interface components

### ISSUE THREAD

**Issue by pkalita-lbl** [cidgoh/DataHarmonizer#312]
In order to improve the ergonomics of integrating DataHarmonizer in downstream projects, I propose making a clearer separation between 1) code for the core components which can be published as a NPM package and 2) the code which builds the interface which users can download and run in their browser locally. Generally speaking this will involve:

* Refactoring code to be written using native JS module syntax, eliminating _all_ global variables
* Use JS bundling tools to produce the necessary artifacts for the library and the local interface
* Use automation tools to perform bundling and publishing as needed

See also: https://github.com/microbiomedata/nmdc-server/issues/623, https://github.com/pkalita-lbl/dh-module-prototype

**Comment by pkalita-lbl** [comment]
@ddooley this is just to track the work we talked about with Mark and Brandon yesterday. I don't have permission to assign to myself, but please feel free to set me as the assignee!

**Comment by ddooley** [comment]
Great, you are on!  For the wider audience, we were discussing how to be able to have DataHarmonizer take advantage of ES6 modules, but at the same time have a local file browser (no server) product as part of a build process - something ES6 modules can't do as they require a web server context.  As well, a dev environment that allows more flexibility in calling up user interface components, and in real-time code testing.
