### ISSUE TITLE
Implement template versioning

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#319]
Currently the DH is versioned as a whole. 

We need a system for versioning templates so we can track how they have changed (the DH may get a version bump, but some templates may not have changed). 

We also need to make finding the template version information clear and easy for users (e.g. in the version description, but then we will need some sort of record keeping system when we update the DH google sheets so we know to update the template version information when we do a new release).

**Comment by ddooley** [comment]
We now have it that each template schema file now contains a version=1.2.3 annotation.  Next step is to add it to DH provenance field output.

**Comment by ddooley** [comment]
As well, we need to get the LinkML specification to accept version (or "class_version") annotation for classes.  Currently only schema can get a version annotation. A LinkML issue has been raised about this. https://github.com/linkml/linkml/issues/868

**Comment by ddooley** [comment]
This is resolved now by using a "version" annotation on a LinkML class (existing LinkML feature).
