### ISSUE TITLE
MPX export to GISAID: headers of the output file need to be updated, remove one field

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#321]
**1.** The headers in the GISAID output file from the MPX templates need to be updated. 
Currently the DH GISAID export is using the same headers as the GISAID CanCOGeN export but GISAID is using MPX-specific headers in the MPX-specific submission form now.
Can we change the MPX headers please?
Keep them as is in the COVID GISAID export.

The COVID-to-MPX header mapping can be in the attached sheet.
[GISAID_covid_to_pox_header_changes_June2022.xls](https://github.com/cidgoh/DataHarmonizer/files/8970913/GISAID_covid_to_pox_header_changes_June2022.xls)

**2.** They have also removed one field for MPX, so we need to remove it too.
The removed field was called "Type" (which was always populated with betacoronavirus in the COVID template).
The header for the Type field was covv_type.
Can we remove this field from the MPX GISAID export please?
Keep it for the COVID GISAID export.

**Comment by ddooley** [comment]
Done!
