### ISSUE TITLE
MPX international template: adjust order of NCBI Biosample export field output

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#325]
Can we tweak the order of the field output in the NCBI Biosample export?

The preferred output order would be:
sample_name
bioproject_accession
attribute_package 
GISAID_accession
GISAID_virus_name
collection_date
collected_by
sequenced_by
sequence_submitted_by
geo_loc_name
organism
isolate
Isolation_source
anatomical_material
anatomical_part
body_product
environmental_material
environmental_site
collection_device
collection_method
lab_host
passage_history
passage_method
host
host_disease
host_health_state
host_disease_outcome
host_age
host_age_unit
host_age_bin
host_sex
host_subject_id
purpose_of_sampling
purpose_of_sequencing
gene_name_1
diagnostic_PCR_CT_value_1
gene_name_2
diagnostic_PCR_CT_value_2
description

attribute_package will need to be added to the output and filled by the user, it won't come from any information supplied in the MPX template.

**Comment by ddooley** [comment]
Done in latest Monkeypox_international commit.  Should a similar reorder happen in CanCoGen?

Collection_date seems to be a new field?
"sample collection date" is removed?
host_age_unit added?
host_age_bin added?

**Comment by griffie** [comment]
I think I reviewed the CanCOGeN Biosample export a few months ago and was ok. Let's leave it for now. :)
