### ISSUE TITLE
absence of a export.js in a template folder -> Unable to load template at path .... Path should consist of [template folder name]/[template name]...

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#326]

**Comment by turbomam** [comment]
linkml.yaml runs to completion. Error appears when loading main.html or changing templates.

**Comment by ddooley** [comment]
Sorry, I'm a dunce!  This is a warning about an "export.js" file that is expected to sit in each template folder - even if it has nothing in it, besides "var EXPORT_FORMATS = {}".

**Comment by ddooley** [comment]
Ok to close this?

**Comment by ddooley** [comment]
Closing as I believe this is resolved.
