### ISSUE TITLE
DH functions still referencing old template format

### ISSUE THREAD

**Issue by Takadonet** [cidgoh/DataHarmonizer#327]
Cannot use functions [getMappedField ](https://github.com/cidgoh/DataHarmonizer/blob/master/script/data-harmonizer/export_utils.js#L139 )and [getTransformedField ](https://github.com/cidgoh/DataHarmonizer/blob/master/script/data-harmonizer/export_utils.js#L166)since they are referencing to the old DataHarmonizer Template. (data.tsv)

**Comment by ddooley** [comment]
Good catch!  Will accept pull now!
