### ISSUE TITLE
Canadian MPX template: Change position of SUBMITTED_RESLT fields in NML-LIMS export output

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#331]
In the Canadian MPX template, the diagnostic PCR fields (each test has a gene target and corresponding CT value) are output in the NML-LIMS export as SUBMITTED_RESLT fields. 
They are capitalized, so can we move them in the LIMS output to just after PH_BIOINFORMATICS_PROTOCOL?

There should be 10 SUBMITTED_RESLT fields in total to be moved.

**Comment by ddooley** [comment]
Done!
