### ISSUE TITLE
Website localization 

### ISSUE THREAD

**Issue by Takadonet** [cidgoh/DataHarmonizer#333]
Possible we can add support for language localization for non template values? My assumption that need one template for each language that we support.

example:
MPX_French
MPX_English

**Comment by ddooley** [comment]
Hi, Philip,

I'll check with the LinkML folks.  We'd really want to provide french labels for fields and picklists directly in 1 single french/english LinkML specification file, and have DataHarmonizer switch between the two in the app.  But they may say to have the DH app handle this via a separate language mapping file.

**Comment by ddooley** [comment]
Also, could you check out https://github.com/cidgoh/DataHarmonizer/pull/329 to see if you have any issues with it, following the yarn instructions and bringing up the test site via yarn dev and via yarn build:web etc. We think its a good way to go but it means that after development, any DH releases you provide your clients via github or wherever are just zip snapshots of the web/dist/ folder after doing yarn build:dist .

**Comment by ddooley** [comment]
Question about MPX_French vs English - I'm assuming all picklists would stay the same?  Field titles, descriptions, guidance picklist item titles, would need translation.

**Comment by Takadonet** [comment]
I was more thinking smaller for now and just localization of everything **but** the template themselves.
![image](https://user-images.githubusercontent.com/64732/179016269-901c6609-a06a-48d4-9d01-a7940d3cddbd.png)

Start small and then work towards the templates themselves later.

**Comment by ddooley** [comment]
Ah, I see. so a DH application translation rather than template content.  Ok, that sounds like a new and important project. I know there are UI phrase lookup and substitution tools for app development we should get going into DH.

**Comment by Takadonet** [comment]
It be another feather in our cap to use DH for large scale projects.

**Comment by ddooley** [comment]
Just a note that a good candidate for browser interface for localization seems to be:  https://www.i18next.com

**Comment by ddooley** [comment]
We can close this now.  It is completed and awaiting final translation in https://github.com/cidgoh/DataHarmonizer/pull/440
