### ISSUE TITLE
Canadian MPX template: change order of fields in NML export output 

### ISSUE THREAD

**Issue by griffie** [cidgoh/DataHarmonizer#335]
New MPX fields in the NML export include different accession numbers which will need to be moved up in the output.

Can the new order go:
HC_CURRENT_ID
SUBMISSIONS - BioProject Accession
SUBMISSIONS - BioSample Accession
SUBMISSIONS - SRA Accession
SUBMISSIONS - GenBank Accession
SUBMISSIONS - GISAID Virus Name
SUBMISSIONS - GISAID Accession

Thanks!

**Comment by ddooley** [comment]
Done!
