### ISSUE TITLE
new issues about horizontal scrolling in DH, as embedded in NMDC portal

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#341]
See https://github.com/microbiomedata/nmdc-server/issues/752

@pkalita-lbl

**Comment by pkalita-lbl** [comment]
I think the issue was in code that `nmdc-server` has built around `DataHarmonizer` and not with `DataHarmonizer` itself. The issue that was referenced has been closed, so I'm closing this as well.
