### ISSUE TITLE
Allow `getDataObjects` to export invalid data

### ISSUE THREAD

**Issue by pkalita-lbl** [cidgoh/DataHarmonizer#350]
Currently the `getDataObjects` method excludes table values that are not mappable to the column's data type (as defined by the schema). NMDC has a use-case where they would like to be able to save in-progress work that may not necessarily be valid. 

I propose adding a `strict` (default `true`) flag to the `getDataObjects` method. If `strict` is true the existing behavior is maintained. If `strict` is false, it should not attempt to parse values based on the column type and return all values as strings.

**Comment by ddooley** [comment]
Yes, lets do that!
