### ISSUE TITLE
DH export tab popping error

### ISSUE THREAD

**Issue by nithujohn** [cidgoh/DataHarmonizer#367]
Hi Damion, Sometimes when I try to export a file in DH the options doesnot show up it appears blank. I  mainly seen this for file which has samples 500+. Also I use Windows operating system and opens in Google Chrome. I am also wondering is that due to internet unstable. Can you please have a look. Thanks :)
![image1](https://user-images.githubusercontent.com/85367999/206318982-666952b3-b907-4478-8b98-6ef2235fa1c7.jpeg)

**Comment by ddooley** [comment]
I presume there are steps you take to try again and succeed?  What would they be?

Also, do you work on a mac? If so when this happens can you press and hold option-command and J keys, and then screen shot the "Console" tab of the popup - usually that's the default. That will tell us if a javascript error has occured.

Thankx,

d.

**Comment by ddooley** [comment]
Woops, I glossed over that you use windows.  On windows you can get the popup javascript console message by clicking on upper-right tripple dot ... menu, then "More Tools > Developer Tools" (bottom menu item).

**Comment by nithujohn** [comment]
When I see the  error I just go back and click the tab again. But sometimes it takes a while to load.

**Comment by ddooley** [comment]
So try to catch console screen to see if there was an error. In meantime if you could send me the dataset that is triggering this error situation I can see if I can replicate.  If however its a function of computer speed/memory etc, then I might have to depend on you to catch error report.

**Comment by nithujohn** [comment]
I have more details this error occurs when I open a DH file plus I try to capture the info but my console didn't show any error :(
![image](https://user-images.githubusercontent.com/85367999/206814465-62dc4817-2c01-4da5-a17f-4acbd17af729.png)

**Comment by ddooley** [comment]
Hi Nithu,
I think you sent me the output file that was successful when it works?  I need the input file that was causing the sporadic output failure.

d.

From: Nithu John ***@***.***>
Reply-To: cidgoh/DataHarmonizer ***@***.***>
Date: Friday, December 9, 2022 at 4:27 PM
To: cidgoh/DataHarmonizer ***@***.***>
Cc: Damion Dooley ***@***.***>, Comment ***@***.***>
Subject: Re: [cidgoh/DataHarmonizer] DH export tab popping error (Issue #367)


I have more details this error occurs when I open a DH file plus I try to capture the info but my console didn't show any error :(
[Image removed by sender. image]<https://user-images.githubusercontent.com/85367999/206814465-62dc4817-2c01-4da5-a17f-4acbd17af729.png>

**Comment by ddooley** [comment]
Ok, I'm not able to replicate the problem on my powerbook, so I'll have to see about testing on a windows machine, perhaps slower machine is the main variable.  Perhaps we can debug it on your computer before a friday lab meeting?

BTW It isn't about internet connection.  The app runs 100% locally, no internet needed.

**Comment by ddooley** [comment]
@nithujohn can you verify if this comes up again with the new version of DH we've been testing. If not, we'll close this.  New handsontable code might resolve it.

**Comment by nithujohn** [comment]
Tested and looks good at my end! thank you
