### ISSUE TITLE
DataHarmonizer should honor LinkML unique_key assertions, for multiple columns with uniqueness constraint

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#369]
Happy new year!

I'm currently evaluating the degree to which LinkML itself honors unique_key assertions. See [UniqueKey class](https://linkml.io/linkml-model/docs/UniqueKey/).

Could be assigned to @pkalita-lbl

**Comment by ddooley** [comment]
Sounds fairly straightforward.  Strkies me that this should have an equivalent rule pattern, i.e. be supported by rule functionality that can spot unique_keys as a combo of slots' values?

**Comment by turbomam** [comment]
I think the support for multiple unique keys was completed, but support for LinkML rules still needs discussion and planning.
