### ISSUE TITLE
Enumerations with a large number of elements are cut off when displaying the entire list

### ISSUE THREAD

**Issue by prolog** [cidgoh/DataHarmonizer#384]
I'm working with an enumeration of 15 elements. When opening a field that uses that enumeration in the UI, only the first 9 values are shown (the 9th is partially cut off), and there's no scrollbar to navigate down and see the rest. Arrow keys work, as does filtering the list of elements via typing - it just appears to be scrolling that's an issue.

**Comment by ddooley** [comment]
The behaviour of this control is set by: https://handsontable.com/docs/javascript-data-grid/dropdown-cell-type/ or https://handsontable.com/docs/javascript-data-grid/autocomplete-cell-type/ . What I'm not seeing is any ability to control visibility of a scrollbar via api parameter or css hack.  Note that this is not an HTML <select> control.  The list is a table relatively positioned, and programmatically moved via javascript that depends entirely on arrows or trackpad finger motions to navigate.  Hmm!



So in your tests I presume a mouse with scrollbar control would also work?  

Short answer is it might be possible to play with the CSS around this table, namely the

**Comment by ddooley** [comment]
Ok, thanks for feedback.  It would be difficult to hack the handsontable code to do anything better, so I'm closing this for now.
