### ISSUE TITLE
When DH creates menus from LinkML enums, it requires the presence of the optional `text` property

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#387]
suggested for @pkalita-lbl

**Comment by pkalita-lbl** [comment]
I'm not totally sure this is a DataHarmonizer issue. This could have more to do with the `gen-linkml` step of transforming a YAML schema in JSON format.

**Comment by turbomam** [comment]
Oh yeah. You did mention that.

**Comment by pkalita-lbl** [comment]
False alarm. This has nothing to do with DataHarmonizer.
