### ISSUE TITLE
Transform URLs in help popup into clickable links

### ISSUE THREAD

**Issue by pkalita-lbl** [cidgoh/DataHarmonizer#388]
If a slot has a `description` that contains a URL, it would be nice if that URL was rendered as a clickable link when it is shown in the help popup. For example:

<img width="512" alt="Untitled" src="https://user-images.githubusercontent.com/102547565/230681207-d250c7e1-1fcf-4862-9ce7-69eb4e270849.png">

**Comment by ssarrafan** [comment]
@pkalita-lbl would it be possible to get this done Monday or Tuesday of next week as a fix?  I'll add it to the next sprint but let me know if you won't have time.

**Comment by pkalita-lbl** [comment]
I'm working on https://github.com/microbiomedata/nmdc-server/issues/945 right now. Is this also a high priority?

**Comment by ddooley** [comment]
Sounds like good functionality.  Only thought was whether one might want to also allow [title](url) style markup links.

**Comment by pkalita-lbl** [comment]
If we go that far should we just support markdown in general? There are plenty of performant, off-the-shelf parsers out there.
