### ISSUE TITLE
Add column help sidebar to core library

### ISSUE THREAD

**Issue by pkalita-lbl** [cidgoh/DataHarmonizer#392]
While using DataHarmonizer within the NMDC project we got feedback that it wasn't immediately apparent to users that double-clicking a column header would give them a help popup. To address that we implemented a collapsible sidebar with the same help information. It updates as the user selects different cells to show help for the selected column. In a brief conversation with some folks at the [Great Lakes Bioenergy Research Center](https://www.glbrc.org/) who are using DataHarmonizer, they also expressed interest in the help sidebar. 

I think it's fair to say a help sidebar is non-application-specific enough to consider adding to the core library.

**Comment by ddooley** [comment]
Yes, I ran this by Emma and it seemed like a fine piece of functionality.  I think your current NMDC implementation has it "squeeze" existing DH display space, rather than float over it, which seems alright too, given that people can turn it off/on.

**Comment by pkalita-lbl** [comment]
That's right. It kind of needs to squeeze instead of overlay because otherwise you couldn't edit the last few columns while still looking at the help.
