### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by gwajnberg** [cidgoh/DataHarmonizer#398]
cloned the repo and tried to run "yarn" but package.json is missing "start":

**Comment by ddooley** [comment]
Hi, perhaps @pkalita-lbl can address this, but the three commands I know of are "yarn dev" to get DH to run in a browser locally; and "yarn build:lib" to compile the core javascript again; and "yarn build:web" to refresh the /web/dist/ folder stand-alone index.html application based on templates provided in /web/templates/

**Comment by ddooley** [comment]
The "yarn dev" command provides browser version of /web/templates/ such that changes to code and templates triggers reload of the browser app.

**Comment by pkalita-lbl** [comment]
Not sure if I have much to add. @ddooley has correctly outlined the relevant scripts for this project. If there is any documentation that suggests running a `start` script, please let us know so we can fix that.

**Comment by ddooley** [comment]
@gwajnberg Can we close this now?

**Comment by gwajnberg** [comment]
Oh yeas it worked sorry!
