### ISSUE TITLE
Schema not loading in DataHarmonizer (only Chrome and Edge; Firefox working)

### ISSUE THREAD

**Issue by jannikseidelQBiC** [cidgoh/DataHarmonizer#402]
Dear developers of the DataHarmonizer,
first of all, thank you for your great work!

I have an issue with loading my self-developed schema with Chrome and Edge (tested on MacOS (ARM) and Windows 11(Intel)). 
The schema does not load with the mentioned browsers (except Firefox, there everything is working). 
The yaml-file is approx. 39 MB and the schema.json approx. 44 MB, so quiet large. I put a few ontologies (the largest is ChEBI, where I only used leaf nodes of the obo graph) into the DataHarmonizer schema as controlled vocabulary. 

Could you tell me if someone has the same problem and possible solutions? (And if it is a DataHarmonizer problem or a browser issue)

Thanks in advance

**Comment by jannikseidelQBiC** [comment]
The large ontology as controlled vocabulary was the problem. Might be of interest for others :)

**Comment by ddooley** [comment]
Ok, thanks for this update.  So you were able to load a smaller version of your schema?  It sounds like to a small schema with "larger" enumerations to work we would need to implement dynamic lookup of terms for enumeration selection lists?

**Comment by jannikseidelQBiC** [comment]
Right, I threw out the validation of chemicals and it worked just fine. It could be that dynamic lookup would solve the problem, I think it would make the insertion of terms smoother (it took up to 15 seconds to load the dialog in firefox).
This is also an interesting point: Why did it work with firefox but not with chrome/edge/safari? I didn't find an answer to that point.
