### ISSUE TITLE
Changing the language should depend on the available user interface locales, not schema locales

### ISSUE THREAD

**Issue by kennethbruskiewicz** [cidgoh/DataHarmonizer#430]
Currently, the locale menu depends on a schema template having a translation. But the user interface translations are offered separately.

The behaviour of the menu should be such that (a) it offers option based on available user interface translations, and (b) signals when for a given user interface translation, a schema translation is also available.

Possibly, the language in the interface and language in the schema could be chosen at load time.

**Comment by ddooley** [comment]
Resolved in upcoming DH2-i18n-rc1 branch.
