### ISSUE TITLE
Importing data and schema configuration from standard JSON file

### ISSUE THREAD

**Issue by kennethbruskiewicz** [cidgoh/DataHarmonizer#435]
Riffing off of this: https://github.com/cidgoh/DataHarmonizer/issues/431#issuecomment-2071096888

given a data structure like:

```json
{
    "schema": "https://www.example.com/GRDI",
    "version": "10.0.0",
    "GRDI_Sample": [ /* list items*/ ],
    "AMR_Test": [ /* list items*/ ]
}
```

we can imagine using the "in_language" property like

```json
{
    "schema": "https://www.example.com/GRDI",
    "version": "10.0.0",
    "in_language": "fr",
    "GRDI_Sample": [ /* list items*/ ],
    "AMR_Test": [ /* list items*/ ]
}
```

This closes the import-export loop for the application, allowing users to save where they left off and have the application state restored to normal. It also means that when the file is passed around, it can self-document what the language content is.

This seems good-enough, with the only possible extension being a self-referential or error-checkable hash that can ensure file integrity.

**Comment by ddooley** [comment]
Good, but as noted in other thread the top-level objects of this should match directly the Container spec in the schema I think, so plural GRDI_Samples, etc...

**Comment by ddooley** [comment]
Resolved in upcoming DH2-i18n-rc1 branch.
