### ISSUE TITLE
exported tsv file for VirusSeq_Portal is not tabulated properly.

### ISSUE THREAD

**Issue by ebi-jlu8** [cidgoh/DataHarmonizer#447]
When I exported the template into a tsv format (VirusSeq_Portal), and checked it in excel, the exported file are not tabulated properly (see pasted image). 
![image](https://github.com/user-attachments/assets/d0b9ede9-4aeb-4544-a970-b1924771edae)

**Comment by ddooley** [comment]
Hi,
Is it the CanCoGen Covid 19 template you are using?  
Can you email me at damion_dooley@sfu.ca the input data file that you are loading into DH?
What it seems in what you are showing is a data file that isn't comma separated OR tab separated. Only first cell in line 2 seems to have delimited data.

**Comment by ebi-jlu8** [comment]
Hi Anton, Yes. This is the  CanCoGen Covid 19 template that I used. I used one of the files from the exampleInput folder - 
[validTestData_2-1-2.xlsx](https://github.com/user-attachments/files/17276683/validTestData_2-1-2.xlsx)
This is the output file when I exported to tsv format. I had to save this as an xls file as git does not allow uploads of tsv:
[example_covid.xls](https://github.com/user-attachments/files/17276718/example_covid.xls)

Thank you

**Comment by ddooley** [comment]
So I'm using the Master branch of DataHarmonizer v 1.7.0 on updated Chrome (and Macbook Air) and exporting to VirusSeq .tsv format and its definitely saving tabs.  What version of DataHarmonizer are you using?  And which browser / OS?

**Comment by ddooley** [comment]
I also tested on PathogenGenomicsPackage GitHub dataharmonizer and it seems fine there too BTW.

**Comment by ebi-jlu8** [comment]
Thanks for looking into this. I am using a macbook (macOS Sonoma v 14.6.1). The DataHarmonizer version I used was the latest one available in the git (v1.6.5) had also created a fork to the original DataHarmonizer git and had been using that. Please find attached a copy of the generated tsv file from the VirusSeq_Portal option. The tsv file seemed to tabulate properly when I open the tsv file in the Apple Numbers app and it tabulated properly. I've tried to open the exported file on my PC laptop (Excel) and it tabulated fine. I have sent a copy of the exported tsv file to your email. 

I have tried using Safari, Google Chrome and Firefox and none of them worked properly.  I am wondering if it is a problem with the version of Mac I am using.
