### ISSUE TITLE
Error at launching DataHarmonizer on web browser

### ISSUE THREAD

**Issue by mmongy** [cidgoh/DataHarmonizer#449]
Hi everyone,

I tried to launch DataHarmonizer locally for trying purposes (to see if it is relevant for our case).  I successfully installed it, but when trying to launch, i have this error (see screen capture)
![Screenshot 2024-10-11 at 16-54-12 DataHarmonizer](https://github.com/user-attachments/assets/3fcf3845-ff88-4252-8e54-320c52017733)

When opening the Firefox console, i have this:

[webpack-dev-server] Server started: Hot Module Replacement enabled, Live Reloading enabled, Progress disabled, Overlay enabled. index.js:485
[HMR] Waiting for update signal from WDS... log.js:39
Uncaught (in promise) TypeError: specification is undefined
    useTemplate DataHarmonizer.js:180
    useSchema DataHarmonizer.js:162
    loadSelectedTemplate Toolbar.js:370

After roughly examining the code, i don't see anything anormal. Did i miss something?

Thanks by advance.

**Comment by ddooley** [comment]
Thanks for reporting this.  It looks like a renaming of one of the example templates wasn't copied over to the menu system, and I have fixed this now.  With an update of your master branch GitHub code, it should work now.  (Assuming you are running this via either "yarn dev" on command line or via "yarn build:web" and then opening "/web/dist/index.html").

Let us know!

Regards,

Damion

**Comment by ddooley** [comment]
@mmongy I imagine this is resolved now?

**Comment by mmongy** [comment]
I'll retry. I was on other things. Thanks anyway.
________________________________
De : Damion Dooley ***@***.***>
Envoyé : jeudi 17 octobre 2024 16:10
À : cidgoh/DataHarmonizer ***@***.***>
Cc : mmongy ***@***.***>; Mention ***@***.***>
Objet : Re: [cidgoh/DataHarmonizer] Error at launching DataHarmonizer on web browser (Issue #449)


@mmongy<https://github.com/mmongy> I imagine this is resolved now?

**Comment by mmongy** [comment]
I tried to relaunch, it works. You solved the problem.

**Comment by ddooley** [comment]
Great, good to hear!
