### ISSUE TITLE
Accession Prefix Validation

### ISSUE THREAD

**Issue by cmrn-rhi** [cidgoh/DataHarmonizer#60]
Implement validation on accessions that have controlled prefixes.

**BioProject Accession** - Prefix: **PRJNA**
**BioSample Accession** - Prefix: **SAMN**
**SRA** (run) **Accession** - Prefix: **SRR**
**GISAID Accession** - Prefix: **EPI_ISL_**

GenBank Accessions - Allowable prefixes for nucleotide direct submissions: **U, AF, AY, DQ, EF, EU, FJ, GQ, GU, HM, HQ, JF, JN, JQ, JX, KC, KF, KJ, KM, KP, KR, KT, KU, KX, KY, MF, MG, MH, MK, MN, MT** (source: https://www.ncbi.nlm.nih.gov/Sequin/acc.html)

**Comment by ivansg44** [comment]
Seems like a good idea to me. @griffie Any problems with us adding this?

**Comment by griffie** [comment]
I think that would be good.

**Comment by ddooley** [comment]
This can be done via a generic regular expression match, i.e. ^(U|AF|AY|DQ|EF|EU etc.)\d+
